theme: jekyll-theme-cayman
include: [".well-known", "./account.html"]

repository: MTL-Association/mtla.github.io
baseurl: ""
url: "https://mtla.me"

timezone: UTC
encoding: "utf-8"

# Plugins
plugins:
  - jekyll-multiple-languages-plugin

# jekyll-multiple-languages-plugin settings:
languages: ["en", "eo", "ru", "uk"]

exclude_from_localizations: ["assets", "_sass", "_layouts", "_includes"]
